name: CI tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.10
        uses: actions/setup-java@v1
        with:
          java-version: 10
      - name: Build
        run: mvn install -Dmaven.test.skip=true
      - name: Run unit tests
        run: mvn test
